// flow-typed signature: 1ebf23b48767100594584a60cd880d15
// flow-typed version: <<STUB>>/lint_v^1.1.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lint/lib/assert/extension' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/formatter' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/formatter/callback' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/formatter/cli' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/formatter/json' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/formatter/textmate' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/formatter/vim' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/formatter/xml' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/index' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/jslint' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/launcher' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/parser' {
  declare module.exports: any;
}

declare module 'lint/lib/lint/vows' {
  declare module.exports: any;
}

declare module 'lint/resource/fixture/invalid-test' {
  declare module.exports: any;
}

declare module 'lint/resource/fixture/valid-test' {
  declare module.exports: any;
}

declare module 'lint/test/assert/extension-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/formatter-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/formatter/callback-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/formatter/cli-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/formatter/json-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/formatter/textmate-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/formatter/vim-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/formatter/xml-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/launcher-test' {
  declare module.exports: any;
}

declare module 'lint/test/lint/parser-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lint/index' {
  declare module.exports: $Exports<'lint'>;
}
declare module 'lint/index.js' {
  declare module.exports: $Exports<'lint'>;
}
declare module 'lint/lib/assert/extension.js' {
  declare module.exports: $Exports<'lint/lib/assert/extension'>;
}
declare module 'lint/lib/lint/formatter.js' {
  declare module.exports: $Exports<'lint/lib/lint/formatter'>;
}
declare module 'lint/lib/lint/formatter/callback.js' {
  declare module.exports: $Exports<'lint/lib/lint/formatter/callback'>;
}
declare module 'lint/lib/lint/formatter/cli.js' {
  declare module.exports: $Exports<'lint/lib/lint/formatter/cli'>;
}
declare module 'lint/lib/lint/formatter/json.js' {
  declare module.exports: $Exports<'lint/lib/lint/formatter/json'>;
}
declare module 'lint/lib/lint/formatter/textmate.js' {
  declare module.exports: $Exports<'lint/lib/lint/formatter/textmate'>;
}
declare module 'lint/lib/lint/formatter/vim.js' {
  declare module.exports: $Exports<'lint/lib/lint/formatter/vim'>;
}
declare module 'lint/lib/lint/formatter/xml.js' {
  declare module.exports: $Exports<'lint/lib/lint/formatter/xml'>;
}
declare module 'lint/lib/lint/index.js' {
  declare module.exports: $Exports<'lint/lib/lint/index'>;
}
declare module 'lint/lib/lint/jslint.js' {
  declare module.exports: $Exports<'lint/lib/lint/jslint'>;
}
declare module 'lint/lib/lint/launcher.js' {
  declare module.exports: $Exports<'lint/lib/lint/launcher'>;
}
declare module 'lint/lib/lint/parser.js' {
  declare module.exports: $Exports<'lint/lib/lint/parser'>;
}
declare module 'lint/lib/lint/vows.js' {
  declare module.exports: $Exports<'lint/lib/lint/vows'>;
}
declare module 'lint/resource/fixture/invalid-test.js' {
  declare module.exports: $Exports<'lint/resource/fixture/invalid-test'>;
}
declare module 'lint/resource/fixture/valid-test.js' {
  declare module.exports: $Exports<'lint/resource/fixture/valid-test'>;
}
declare module 'lint/test/assert/extension-test.js' {
  declare module.exports: $Exports<'lint/test/assert/extension-test'>;
}
declare module 'lint/test/lint/formatter-test.js' {
  declare module.exports: $Exports<'lint/test/lint/formatter-test'>;
}
declare module 'lint/test/lint/formatter/callback-test.js' {
  declare module.exports: $Exports<'lint/test/lint/formatter/callback-test'>;
}
declare module 'lint/test/lint/formatter/cli-test.js' {
  declare module.exports: $Exports<'lint/test/lint/formatter/cli-test'>;
}
declare module 'lint/test/lint/formatter/json-test.js' {
  declare module.exports: $Exports<'lint/test/lint/formatter/json-test'>;
}
declare module 'lint/test/lint/formatter/textmate-test.js' {
  declare module.exports: $Exports<'lint/test/lint/formatter/textmate-test'>;
}
declare module 'lint/test/lint/formatter/vim-test.js' {
  declare module.exports: $Exports<'lint/test/lint/formatter/vim-test'>;
}
declare module 'lint/test/lint/formatter/xml-test.js' {
  declare module.exports: $Exports<'lint/test/lint/formatter/xml-test'>;
}
declare module 'lint/test/lint/launcher-test.js' {
  declare module.exports: $Exports<'lint/test/lint/launcher-test'>;
}
declare module 'lint/test/lint/parser-test.js' {
  declare module.exports: $Exports<'lint/test/lint/parser-test'>;
}
