// flow-typed signature: 9e905b75051d855ba9d36e1b27514968
// flow-typed version: <<STUB>>/mdi_v^2.0.46/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mdi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mdi' {
  declare module.exports: any;
}
